"""
知識抽出処理の設定値
"""

# 知識抽出の処理設定
KNOWLEDGE_EXTRACTION_TIMEOUT = 30  # 秒
KNOWLEDGE_EXTRACTION_RETRY_COUNT = 3

# バリデーション設定
MIN_KNOWLEDGE_DESCRIPTION_LENGTH = 5
MAX_KNOWLEDGE_DESCRIPTION_LENGTH = 500

# ログ出力設定
KNOWLEDGE_EXTRACTION_DEBUG_ENABLED = True

# フィルタリング設定
EXCLUDE_EMPTY_KNOWLEDGE = True
EXCLUDE_DUPLICATE_KNOWLEDGE = True